name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: 'The deployment environment'
        required: true
        type: environment

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      build_name: ${{ needs.build.outputs.build_name }}
      environment: ${{ inputs.environment }}
    secrets: inherit
